import { prisma } from '../prisma';

export async function createCustomerFlag(
    customerId: string,
    reason: string,
) {
    // check if customer exists
    const customer = await prisma.customer.findUnique({
        where: { id: customerId }
    });

    // if customer does not exist, return null
    if (!customer) {
        return null;
    }

    // create a new flag for the customer
    const flag = await prisma.flag.create({
        data: {
            reason, 
            customerId,
        }
    });
    //  flag contains the full newly created database row, not just the fields you passed in.
    // Prisma does two things:
    // Inserts a new row into the flag table
    // Returns the entire created record as a JavaScript object
    // So flag will contain all columns from your flag table, including:
    // id (auto‑generated by Prisma/DB)
    // reason (the value you passed)
    // customerId (the value you passed)
    // createdAt (if your schema has it)
    // updatedAt (if your schema has it)
    // Any other fields defined in your Prisma model
    return flag;
}